image: python:3.9

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  CODE: "app config database"

cache:
  paths:
    - .cache/pip
    - .venv/

before_script:
  - python -V
  - python -m venv .venv
  - source .venv/bin/activate
  - python -m pip install --upgrade pip
  - python -m pip install poetry
  - poetry install

stages:
  - lint
  - test

lint:
  stage: lint
  script:
    - flake8 --jobs 4 --statistics --show-source $CODE
    - pylint --jobs 4 --rcfile=setup.cfg $CODE
    - mypy $CODE
    - black --line-length 79 --target-version py39 --skip-string-normalization --check $CODE
    - pytest --dead-fixtures --dup-fixtures
    - safety check --full-report

test:
  stage: test
  script:
    - pytest --verbosity=2 --showlocals --log-level=DEBUG --cov
