name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  lint:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      
    - name: Install dependencies
      run: make
      
    - name: Install poetry
      run: make venv
      
    - name: Run lint
      run: make lint

  test:
    runs-on: ubuntu-latest
    needs: [lint]
    services:
      postgres:
        image: postgres:14.5
        env:
          POSTGRES_DB: data
          POSTGRES_USER: pguser
          POSTGRES_PASSWORD: pgpswd
          POSTGRES_HOST: postgres
          POSTGRES_PORT: 5432
    steps:
      - name: Run tests
        run: make test
